ansible_run/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path("", views.go_index, name="go_index"),
    path("go_result_page/<str:task_id>/", views.go_result_page, name="go_result_page"),
    path('go_task_list/', views.go_task_list, name='go_task_list'),
    path('get_csrf_token/', views.get_csrf_token, name='get_csrf_token'),
    path('get_result/<str:task_id>/', views.get_result, name='get_result'),

    # api
    path('api/tasks/cancel-task', views.cancel_task_view, name='cancel_task_api'),

    path('api/tasks/get-list', views.get_task_list_api, name='get_task_list_api'),
    path('api/ansible-run', views.ansible_run, name='ansible_run'),

]

host_manager/urls.py
from django.urls import path
from .views import HostCreateView, HostUpdateView, HostDeleteView
from . import views

# app_name = 'host_manager'
urlpatterns = [
    path('', views.go_host_manager, name='go_host_manager'),
    path('create/', HostCreateView.as_view(), name='host_create'),
    path('update/<int:pk>/', HostUpdateView.as_view(), name='host_update'),
    path('delete/<int:pk>/', HostDeleteView.as_view(), name='host_delete'),

    # API
    path('api/hosts/batch-delete/', views.batch_delete, name='batch_delete_host_api'),
    path('api/hosts/host-list//', views.get_hosts_list_api, name='get_host_list_api'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include(('userlogin.urls','login'), namespace='login')),
    path('scripts/',include(('scripts.urls','playbook'),namespace='scripts'),name='scripts'),
    path('', include(('ansible_run.urls', 'ansible_run'),namespace='ansible_run'), name='ansible_run'),
    path('runner_jobs/', include(('runner_jobs.urls', 'runner_jobs'),namespace='runner_jobs')),
    path('host_manager/', include(('host_manager.urls', 'host_manager'),namespace='host_manager'), name='host_manager'),

]

userlogin/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    path("register/", views.register, name="register"),
    path("", views.login, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("forget_password/", views.forget_password, name="forget_password"),
    path('reset-password/', views.MyPasswordResetView.as_view(), name='password_reset'),
    path('reset-password/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url='/'),
         name='password_reset_confirm'),
    path('reset-password/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

ansible_run/models.py
from django.db import models
from runner_jobs.models import Job
# Create your models here.
class CeleryTask(models.Model):


    task_id = models.CharField(max_length=255, primary_key=True)  # 任务唯一标识
    created_at = models.DateTimeField(auto_now_add=True)  # 创建时间
    is_used = models.BooleanField(default=False, verbose_name="是否已使用")  # 新增字段
    job = models.ForeignKey(
        Job,
        on_delete=models.CASCADE,
        related_name='celery_tasks',  # 用于从 Job 反向访问所有 CeleryTask
        verbose_name='所属任务'
    )
    class Meta:
        verbose_name = "Celery任务记录"
        verbose_name_plural = "Celery任务记录"

    def __str__(self):
        return self.task_id

ansible_run/views.py
import json

from celery.result import AsyncResult
from cryptography.fernet import InvalidToken
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse, JsonResponse
from django.middleware.csrf import get_token
from django.shortcuts import render, redirect
from django.views.decorators.csrf import ensure_csrf_cookie

from runner_jobs.models import Job
from .models import CeleryTask
from host_manager.models import Host
from .tasks import run_ansible_playbook, cancel_task
import re


# 跳转页面
@login_required(login_url="/login")
def go_index(request):
    return render(request, 'index.html')


@login_required(login_url="/login")
def go_task_list(request):
    return render(request, 'task_list.html')


@login_required(login_url="/login")
def go_result_page(request, task_id):
    return render(request, 'getResult.html', context={'task_id': task_id})


# 执行任务并将id入库
@login_required(login_url="/login")
def ansible_run(request):
    if request.method == 'POST':
        try:

            data = json.loads(request.body)
            # print()
            hosts = data.get('inventory', '[]')

            hosts_info = Host.objects.filter(ip__in=hosts, users=request.user).values('ip', 'port', 'username',
                                                                                      'ssh_password_encrypted',
                                                                                      'become_password_encrypted')

            job_id = data.get('job_id')
            if not job_id:
                return JsonResponse({'error': '缺少 job_id'}, status=400)

                # 获取对应的 Job 对象

            job = Job.objects.get(id=job_id)

            print('job:',job_id)
            if not hosts_info.exists():
                return JsonResponse({'error': '未找到对应的目标主机'}, status=400)
            # print(data['playbook_content'])

            hosts_queryset = Host.objects.filter(ip__in=hosts, users=request.user)
            # 提取密码
            for host in hosts_queryset:
                try:
                    ssh_pass = host.get_ssh_password()
                except InvalidToken:
                    ssh_pass = None
                    print(f"[警告] 主机 {host.ip} 的 SSH 密码解密失败")

                try:
                    become_pass = host.get_become_password()
                except InvalidToken:
                    become_pass = None
                    print(f"[警告] 主机 {host.ip} 的提权密码解密失败")

            # 构建 inventory 字典格式
            inventory_dict = {
                "test": {
                    "hosts": {
                        host_info['ip']: {
                            "ansible_host": host_info['ip'],
                            "ansible_port": host_info['port'],
                            "ansible_user": host_info['username'],

                            # 添加其他需要的信息
                        }
                        for host_info in hosts_info
                    }
                }
            }

            # 构造 kwargs 字典
            kwargs = {
                'playbook': data['playbook_content'],  # playbook内容 （没有与Playbook管理做动态绑定，Playbook内容编辑之后需要新建任务）
                'job_type': data.get('job_type'),  # 任务类型
                'inventory': inventory_dict,
                'verbosity': data.get('verbosity'),  # 结果显示等级
                'forks': data.get('forks'),  # 并发量
                'module_args': data.get('module_args'),  # 模块参数
                'extra_vars': data.get('extra_vars'),  # 扩展变量
                'module_name': data.get('module_name'),  # 模块名称
                'ssh_pass': ssh_pass,
                'become_pass': become_pass,
            }
            # print(module_name, module_args)
            # 传参执行任务
            task_id = run_ansible_playbook.delay(**kwargs)

            #task任务绑定job任务
            celery_task = CeleryTask(task_id=task_id,job=job)
            celery_task.save()

            json_data = {
                'task_id': task_id.task_id

            }
            return JsonResponse(json_data)
        except Exception as e:

            return JsonResponse({'error': str(e)}, status=500)


# 停止任务
@login_required(login_url="/login")
def cancel_task_view(request):
    if request.method == 'POST':
        body = json.loads(request.body)

        task_id = body.get('taskId')

        cancel_task.delay(task_id)
        return JsonResponse({'status': 'Task cancellation requested'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid request method'}, status=405)


# 获取任务日志
@login_required(login_url="/login")
def get_task_list_api(request):
    page = request.GET.get('page', 1)
    limit = request.GET.get('limit', 5)

    # tasks = CeleryTask.objects.values().order_by('-created_at')  # 获取所有任务并按创建时间排序
    tasks = CeleryTask.objects.select_related('job').filter(job__user=request.user).order_by('-created_at')
    paginator = Paginator(tasks, limit)
    try:
        page_tasks = paginator.page(page)
    except PageNotAnInteger:
        page_tasks = paginator.page(1)
    except EmptyPage:
        page_tasks = paginator.page(paginator.num_pages)
    # 初始化空列表
    data = []

    # 遍历 tasks 中的每个元素
    for item in page_tasks:
        # 构造字典并添加到列表
        job = item.job
        print(item)
        data.append({
            'job_name': job.name if job else None,
            'job_type': job.job_type if job else None,
            'job_id': str(job.id) if job else None,
            'task_id': item.task_id,
            'created_at': item.created_at,
            'is_used': item.is_used
        })

    json_data = {
        'code': 0,
        'count': paginator.count,
        'data': data
    }

    return JsonResponse(json_data)


# csrf返给前端使用
@ensure_csrf_cookie  # 确保返回 CSRF 令牌
def get_csrf_token(request):
    return JsonResponse({'csrfToken': get_token(request)})


# 获取结果
@login_required(login_url="/login")
def get_result(request, task_id):
    # task_id = request.GET.get('task_id')
    # print('获取一下iD', task_id)
    if not task_id:
        return JsonResponse({'error': '缺少任务ID'}, status=400)

    task = AsyncResult(task_id)
    return JsonResponse({
        'status': task.status,
        'stdout': task.result.get('stdout', '') if task.ready() else '',
        'stderr': task.result.get('stderr', '') if task.ready() else '',
        'rc': task.result.get('rc', -1) if task.ready() else -1
    })

ansible_run/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Ansible Pilot</title>
    <meta name="csrf-token" content="{{ csrf_token }}">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'layui.css' %}" rel="stylesheet">
    <script src="{% static 'layui.js' %}"></script>
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>

    <style>
        .layui-card-body{

        }

    </style>
</head>
<body>

<div class="layui-layout layui-layout-admin">
    <div class="layui-header">
        <div class="layui-logo layui-hide-xs ">
            <h3><a style="color: whitesmoke" href="{% url 'ansible_run:go_index' %}">Ansible Pilot</a></h3>
        </div>
        <!-- 头部区域（可配合layui 已有的水平导航） -->
        <ul class="layui-nav layui-layout-left">
            <!-- 移动端显示 -->
            <li class="layui-nav-item layui-show-xs-inline-block layui-hide-sm" lay-header-event="menuLeft">
                <i class="layui-icon layui-icon-spread-left"></i>
            </li>
            {#            <li class="layui-nav-item layui-hide-xs"><a href="{% url 'ansible_run:go_index' %}">首页</a></li>#}
            {#            <li class="layui-nav-item layui-hide-xs"><a href="{% url 'ansible_run:go_task_list' %}">任务列表</a></li>#}
            {#            <li class="layui-nav-item layui-hide-xs"><a href="{% url 'host_manager:go_host_manager' %}">主机管理</a></li>#}
            {#            <li class="layui-nav-item layui-hide-xs"><a href="{% url 'playbook:list_page' %}">Playbook管理</a></li>#}
            {#            <li class="layui-nav-item layui-hide-xs"><a href="{% url 'playbook:list_page' %}"></a></li>#}

        </ul>
        <ul class="layui-nav layui-layout-right">
            <li class="layui-nav-item layui-hide layui-show-sm-inline-block">
                <a href="javascript:;">
                    <img src="//unpkg.com/outeres@0.0.10/img/layui/icon-v2.png" class="layui-nav-img">
                    {{ user.username }}

                </a>
                <dl class="layui-nav-child">
                    <dd><a href="javascript:;">Your Profile</a></dd>
                    <dd><a href="javascript:;">Settings</a></dd>
                    <dd><a href="{% url 'login:logout' %}">退出登录</a></dd>

                </dl>
            </li>

        </ul>

    </div>

    <div class="layui-side layui-bg-black">
        <div class="layui-side-scroll">
            <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
            <ul class="layui-nav layui-nav-tree" lay-filter="test">
                <li class="layui-nav-item layui-nav-itemed">
                    <a class="" href="javascript:;">Ansib任务</a>
                    <dl class="layui-nav-child">
                        <dd><a style="color: whitesmoke" href="{% url 'ansible_run:go_index' %}">任务管理</a>
                        </dd>

                        <dd>
                            {#                            <a href="{% url 'ansible_run:go_task_list' %}">任务日志</a>#}
                            <a href="{% url 'ansible_run:go_task_list' %}">任务日志</a>

                        </dd>
                        <dd>
                            <a href="{% url 'host_manager:go_host_manager' %}">主机管理</a>
                        </dd>
                        <dd><a href="{% url 'playbook:list_page' %}">脚本管理</a></dd>
                    </dl>
                </li>
                {#                <li class="layui-nav-item">#}
                {#                    <a href="javascript:;">menu group 2</a>#}
                {#                    <dl class="layui-nav-child">#}
                {#                        <dd><a href="javascript:;">list 1</a></dd>#}
                {#                        <dd><a href="javascript:;">list 2</a></dd>#}
                {#                        <dd><a href="javascript:;">超链接</a></dd>#}
                {#                    </dl>#}
                {#                </li>#}
                {#                <li class="layui-nav-item"><a href="javascript:;">click menu item</a></li>#}
                {#                <li class="layui-nav-item"><a href="javascript:;">the links</a></li>#}
            </ul>
        </div>
    </div>
    <div class="layui-body">
        <!-- 内容主体区域 -->
        <div style="padding: 15px;">
            <div class="layui-card layui-panel">
                <div class="layui-card-header">
                    {% block title %}

                    {% endblock %}
                </div>
                <div class="layui-card-body">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>

        </div>
    </div>
    {#  <div class="layui-footer">#}
    {#    <!-- 底部固定区域 -->#}
    {#    底部固定区域#}
    {#  </div>#}
</div>

<script>

    //JS
    layui.use(['element', 'layer', 'util'], function () {
        var element = layui.element;
        var layer = layui.layer;
        var util = layui.util;
        var $ = layui.$;

        //头部事件
        util.event('lay-header-event', {
            menuLeft: function (othis) { // 左侧菜单事件
                layer.msg('展开左侧菜单的操作', {icon: 0});
            },
            menuRight: function () {  // 右侧菜单事件
                layer.open({
                    type: 1,
                    title: '更多',
                    content: '<div style="padding: 15px;">处理右侧面板的操作</div>',
                    area: ['260px', '100%'],
                    offset: 'rt', // 右上角
                    anim: 'slideLeft', // 从右侧抽屉滑出
                    shadeClose: true,
                    scrollbar: false
                });
            }
        });
    });
</script>
</body>
</html>

ansible_run/templates/getResult.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ansible Playbook Runner</title>
    <!-- 引入 jQuery -->
    <link href="{% static 'layui.css' %}" rel="stylesheet">
    <script src="{% static 'layui.js' %}"></script>
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script
</head>
<body>
<div class="layui-container">
    <div class="layui-row">
        <div class="layui-col-sm12">

            <div class="task-info">
                <h3>任务ID: <span id="task-id">-</span></h3>
            </div>

            <div id="error-message" class="error" style="display: none;"></div>

            <div class="output-area" id="output-area">
                <h3>标准输出 (STDOUT):</h3>
                <pre id="stdout"></pre>
                <h3>标准错误 (STDERR):</h3>
                <pre id="stderr"></pre>
                <h3>返回码 (RC): <span id="rc"></span></h3>
            </div>


        </div>
    </div>

</div>


<script>

    layui.use(function () {
        // code
        layui.code({
            langMarker: true,
            header: true,
            lang: 'bash',
            elem: '.code-demo',
        });
    });

    $(document).ready(function () {
            let csrftoken = null;
            $.get('/get_csrf_token/', function (data) {
                csrftoken = data.csrfToken;
            });
// 自动获取任务ID

            const taskId = "{{ task_id }}";
            console.log(taskId)
            $('#task-id').text(taskId || '未获取到任务ID');

// 检查任务状态
            function checkStatus() {
                $('#loading').show();
                {#$('#check-status').prop('disabled', true);#}
                $('#error-message').hide();

                $.ajax({
                    url: `/get_result/${taskId}`,
                    method: 'GET',
                    dataType: 'json',
                    success: function (data) {
                        {#console.log(data)#}
                        if (data.status === 'pending') {
                            $('#error-message').html('任务仍在执行中...').show();
                            return;
                        }

// 更新输出内容
                        rc = data.rc + "";
                        console.log()
                        $('#stdout').text(data.stdout || '(无输出)');
                        $('#stderr').text(data.stderr || '(无错误)');
                        $('#rc').text(rc || '未返回');


                    }
                    ,
                    error: function (jqXHR, textStatus, errorThrown) {
                        $('#error-message').html(`请求失败: ${textStatus}`).show();
                    }
                    ,
                    complete: function () {
                        $('#loading').hide();
                        {#$('#check-status').prop('disabled', false);#}
                    }
                });
            }

// 初始检查
            checkStatus();
// 每5秒自动刷新
            setInterval(checkStatus, 5000);
        }
    )
    ;
</script>
</body>
</html>

ansible_run/templates/task_list.html
{% extends 'base.html' %}
{% block title %}
    <h2>任务日志</h2>

{% endblock %}
{% block content %}
    <table class="layui-hide" id="test" lay-filter="test"></table>

    <script>

        layui.use(['table', 'dropdown'], function () {
            var table = layui.table;
            var dropdown = layui.dropdown;
            // 单元格事件处理

            table.on('tool(test)', function (obj) {
                console.log(obj)
                if (obj.event == 'details') {

                    task_id = obj.data.task_id
                    console.log(task_id)
                    layer.open({
                        type: 2, // page 层类型
                        area: ['700px', '600px'],
                        title: 'Hello layer',
                        scrollbar: false,

                        maxmin: true, // 允许全屏最小化
                        content: '/go_result_page/' + task_id
                    });

                }
            })
            table.render({
                elem: "#test",
                url: '{% url 'ansible_run:get_task_list_api' %}',
                page: true, // 是否显示分页
                limits: [5, 10, 50, 100, 200],
                limit: 5,// 每页默认显示的数量
                skin: 'line',
                {#toolbar: true,#}
                cols: [[
                    {
                        field: 'job_name',
                        title: '任务名称',
                        maxWidth: 180,

                    },

                    {
                        field: 'job_type',
                        title: '任务类型',
                        maxWidth: 100,

                    },
                    {
                        field: 'created_at',
                        title: '创建时间',
                        sort: true,
                        maxWidth: 200,


                    },
                    {
                        field: 'task_id',
                        title: 'task_id'
                    },
                    {
                        title: "详情",
                        maxWidth: 80,
                        templet: ' <button type="button" lay-event="details" class="layui-btn layui-btn-xs">详情</button>',
                    }
                ]]
            })

        })

    </script>
{% endblock %}